INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(1, 'Guayaba x1kg', 'guayaba.png',2000, 1000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(2, 'Carne de cordero x500g', 'carnecordero.png',40, 10000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(3, 'Cebolla larga x250g', 'cebollalarga.jpg', 50 , 500,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(4, 'Trucha x500g', 'trucha.PNG', 800, 8000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(5, 'Guanabana x1kg', 'guanabana.jpg', 60 , 3000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(6, 'Carne en bistec x500g', 'carnebistec.png', 20, 8500,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(7, 'Huevos de codorniz x24', 'huevoscodorniz.PNG', 300, 8000,'Huevos y derivados lacteos');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(8, 'Fresas x500g', 'fresas.jpeg', 50, 2500,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(9, 'Cebolla morada x500g', 'cebollamorada.jpg', 80, 1500,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(10, 'Papa parda x1kg', 'papaparda.jpg', 40, 3000,'Despensa');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(11, 'Yogurth Botella x3L', 'yogurthbotella.PNG',50, 3000,'Huevos y derivados lacteos');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(12, 'Yuca x1kg', 'yuca.png', 100, 1500,'Despensa');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(13, 'Queso x300g', 'queso.png',1000, 5000,'Huevos y derivados lacteos');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(14, 'Naranja x2kg', 'prod1.png', 500, 2000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(15, 'Pollo entero de campo', 'polloentero.png',1000, 25000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(16, 'Remolacha x1kg', 'remolacha.jpg', 700, 2000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(17, 'Mango Tommi x1kg', 'mango.jpeg', 300, 2000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(18, 'Costilla de cerdo x1kg', 'costillacerdo.png', 500, 11000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(19, 'Panal de huevos Tipo A', 'huevos.png',500, 9500,'Huevos y derivados lacteos');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(20, 'Costilla de cordero x1kg', 'costillacordero.png', 500, 15000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(21, 'Zanahoria x500g', 'zanahoria.png', 1000, 2000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(22, 'Filete tilapia x1kg', 'filetetilapia.png', 600, 12000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(23, 'Mantequilla x200g', 'mantequilla.png', 1000, 2000,'Huevos y derivados lacteos');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(24, 'maracuya x500g', 'maracuya.jpg',1000, 1000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(25, 'Filete salmón x1kg', 'filetesalmon.png', 500, 14000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(26, 'Banano x500g', 'banano.jpg', 20 , 1000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(27, 'Pargo Rojo x500g', 'pargorojo.png',100, 18000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(28, 'Piña x500g', 'piña.png',1000, 3000,'Frutas y verduras');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(29, 'Leche caja x1L', 'leche.png',600, 3500,'Huevos y derivados lacteos');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(30, 'Carne molida x500g', 'carnemolida.png',30, 8000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(31, 'Camarones x500g', 'camarones.png',10, 22000,'Pollo, Carne y Pescados');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(32, 'Arroz x500g', 'arroz.PNG',60, 1400,'Despensa');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(33, 'Frijol x500g', 'frijol.PNG',90, 2500,'Despensa');
INSERT INTO productos(ID, NOMPRODUCTO, RUTAIMAGEN, CANTIDAD, PRECIO, TIPO) values(34, 'Garbanzo x500g', 'garbanzo.PNG',90, 2300,'Despensa');


